# Generated by Django 4.2.3 on 2023-07-12 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_remove_user_followed_follow'),
    ]

    operations = [
        migrations.AddField(
            model_name='follow',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
