# Generated by Django 4.2.3 on 2023-07-15 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_follow_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follow',
            name='active',
        ),
    ]
